const constants = {
    SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
    FETCH_MESSAGES_SUCCESS: 'FETCH_MESSAGES_SUCCESS',
    CREATE_CONVERSATION_SUCCESS: 'CREATE_CONVERSATION_SUCCESS',
}

export default constants;
